version: '3.8'
services:
  mongodb:
    image: mongodb/mongodb-community-server
    ports:
      - 27017:27017
    environment:
      - MONGODB_INITDB_ROOT_USERNAME=${MONGO_ADMIN_USER}
      - MONGODB_INITDB_ROOT_PASSWORD=${MONGO_ADMIN_PASSWORD}
      - MONGODB_INITDB_DATABASE=${DB_NAME}
    volumes:
      - mongo-data:/data/db
      - ./init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro

  backend:
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    environment:
      - MONGO_ADDRESS=mongodb
      - MONGO_PORT=27017

      - DB_NAME=${DB_NAME}

      - MONGO_USER=${MONGO_USER}
      - MONGO_PASSWORD=${MONGO_PASSWORD} 
volumes:
  mongo-data:
  